import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const ProfilePage: NextPage = () => {
  // Start fetching data as soon as possible
  api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-300 md:max-w-2xl">
          <div>Profile View</div>
        </div>
      </main>
    </>
  );
};

export default ProfilePage;
